config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  devise_for :users
  delete "books/:id" => "books#destroy", as: "destroy_book"
  resources :books, only: [:new, :create, :index, :edit, :update, :show]
  resources :sessions, only: [:new]
  resources :users, only: [:show,:edit,:index,:update]
  resources :homes, only: [:top, :about]
  get "/home/about" => "homes#about"
  post "/books" => "books#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    # attachment :image

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  # has_many :post_images, dependent: :destroy
  attachment :image
  attachment :profile_image

  validates :introduction, length: { maximum: 50 }
  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    # added_attrs = [:profile_image,:user_name, :email, :password, :password_confirmation, :remember_me]
    # devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    # devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
 end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    @user_name = current_user.name
    @user_intro = current_user.introduction
    render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
    # @user = current_user.id
    @user_name = current_user.name
    @user_intro = current_user.introduction
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book
    @user_name = current_user.name
    @books = Book.all
    books = @books
    @books_current = current_user.books
    @user_intro = current_user.introduction
  end

  def edit
    @book = Book.find(params[:id])
    # if @book.user == current_user
    #   redirect_to edit_book_path(current_user.id)
    # else
    #   render "index"
    # end
    @user = @book.user
    if @user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

    private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
    @user_i = current_user
    @user = current_user.id
    @user_name =  current_user.name
    @user_intro = current_user.introduction
  end

  def show
    @book_new = Book.new
    @user = User.find(params[:id])
    # @books = Book.find(current_user.id).all
    @books = Book.all
    books = @books
    @books_current = @user.books
    @user_intro = current_user.introduction
    @user_current = current_user.id
  end

  def edit
    @user = User.find(params[:id])
    # if @book.user == current_user
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "Welcome! You have signed up successfully."
    redirect_to user_path(@user.id)
    else
    render "edit"
    end
  end

  def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/book.html.erb
<h1>bookの詳細画面</h1>

app/views/books/edit.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this obj from being saved:
        <% @book.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
      <% end %>
 <!-- <form action="/books/" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="patch"><input type="hidden" name="authenticity_token" value="+hMfSQVCO1rFRxYhDomIbCdq8qfgr8mFJjNSu3YkWD/rIaJ5wmlo59PKiy1dCFOsAIA6nQw9iBm0vleIVQWoeA==">-->
 <!--   <div class="form-group">-->
 <!--     <label for="book_title">Title</label>-->
 <!--     <input class="form-control book_title" type="text" value= name="book[title]" id="book_title">-->
 <!--   </div>-->
 <!--   <div class="form-group">-->
 <!--     <label for="book_opinion">Opinion</label>-->
 <!--     <input class="form-control book_opinion" type="text" value= name="book[opinion]" id="<book_opinion></book_opinion>">-->
 <!--   </div>-->
 <!--    <div class="form-group">-->
 <!--      <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="/books/">-->
 <!--    </div>-->
 <!--</form>-->

 <%= form_with model:@book, local:true do |f| %>
  <label for="inputTitle">Title</label>
  <%= f.text_field :title, autofocus: true, id:"inputTitle" %>
  <label for="inputBody">Opinion</label>
  <%= f.text_field :body, autofocus: true, id:"inputBody" %>
  <%= f.submit "Update Book", class: "btn btn-success" %>
<% end %>


  		<%= link_to "Show", book_path(@book) %> |
  		<a class="back" href="/books">Back</a>
    </div>
  </div>
      </div>
</main>

app/views/books/index.html.erb
<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
</head>

<main>
        <%= flash[:notice] %>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>件のエラーが発生しました
          <% @book.errors.full_messages.each do |message| %>
          <%= message %>
          <% end %>
        <% end %>
  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
     <!--ここにプロフの画像を乗っけたい-->
     <!--完成させようの2-5 かなり下らへんにあり-->
     <!--<img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg">-->
     <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
     <!--<img class="attachment user profile_image fallback" src="/bookers2/app/assets/images/no_image.jpg">-->
      <!--<img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg">-->
    <table class="table">
  <tbody>
    <tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user_name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user_intro %></th>
  </tr>
</tbody>
</table>

<div class="row">
  <div class = "btn-user">
<%= link_to edit_user_path(current_user.id), :method => :get do %>
  <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
<% end %>
  </div>
</div>

<!--      <form action="/books" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="lwqQwXcQfdaT0Gq5XMto+R6XLorraUZxnfYaBdOgJx7fH3ovjd86iHZq3gQLxzp/ufR5DQC62uYC8Mt/ng2Ifw==">-->
<!--  <div class="form-group">-->
<!--    <label for="book_title">Title</label>-->
<!--    <input class="form-control book_title" type="text" name="book[title]" id="book_title">-->
<!--  </div>-->
<!--  <div class="form-group">-->
<!--    <label for="book_opinion">Opinion</label>-->
<!--    <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>-->
<!--  </div>-->
<!--  <div class="form-group">-->
<!--    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">-->
<!--  </div>-->
<!--</form>-->
<h2 class="mt-3">New book</h2>
<!--<form action="/books" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓">-->
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


  <%= form_with model: @book, url:"/books", local:true do|f|%>
    <div class ="field">
    <h4>Title</h4>
    <%= f.text_field :title %>
    </div>
    <div class ="field">
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    </div>
    <div class ="action">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>
  </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
  <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>
  <tbody>
    <% @books.each do|b| %>
      <tr>
        <td><%= link_to user_path(b.id) do %>
            <%= attachment_image_tag b.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
            <% end %>
            </td>
        <!--<td><a href="/a></td>-->
        <td><%=link_to b.title, book_path(b.id)%></td>
        <td><%= b.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>
</main>

app/views/books/show.html.erb
<main>
        <%= flash[:notice] %>
        <div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <!--<img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg">-->
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class = "table ">
  <tbody>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
  </tbody>
  </table>    

<div class="row">
  <div class = "btn-user">
<%= link_to edit_user_path(@user.id), :method => :get do %>
  <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
<% end %>
  </div>
</div>
      <h2 class="mt-3">New book</h2>
      <form action="/books" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="pMW6Ca5OeVw4DPy5UUrMOhM8bxVlLF2HEKkoS0dBTSXs0FDnVIE+At22SAQGRp68tF84ko7/wRCPr/kxCuziRA==">
  <div class="form-group">
    <label for="book_title">Title</label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
</form>
    </div>
    <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody>
      <tr>
        <!--<td><a href="/users/#{b.id}">-->
        <!--  <img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg">-->
        <!--    </a></td>-->
            <td><%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%><br>
              <%= @user.name %>
              <% end %>
              </td>
            <td><%= link_to user_path(@user.id) do %>
              <%= @book.title %>
              <% end %>
            </td>
        <td><%= @book.body %></td>
        <%  if @user.id == current_user.id %>
        <td><%= link_to " Edit", edit_book_path(@book), class: "btn btn-success" %></td>
        <td><%= link_to "Destroy", destroy_book_path(@book), method: :delete, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
      </tbody></table>
    </div>
  </div>
</div>
      </main>

app/views/users/index.html.erb
<main>
  <%= flash[:notice] %>
  <div class="container px-5 px-sm-0">
   <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <!--<img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg">-->
      <%= attachment_image_tag @user_i, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
  <tbody>
    <tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user_name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user_intro %></th>
  </tr>
</tbody>
</table>

<div class="row">
  <div class = "btn-user">
<%= link_to edit_user_path(current_user.id), :method => :get do %>
  <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
<% end %>
  </div>
</div>
<!--<div class="row">-->
<!--  <a class="btn btn-outline-secondary btn-block fas fa-user-cog" href="users/>/edit"></a>-->
<!--</div>-->
     <h2 class="mt-3">New book</h2>
<!--<form action="/books" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓">-->
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


  <%= form_with model: @book, url:"/books", local:true do|f|%>
    <div class ="field">
    <h4>Title</h4>
    <%= f.text_field :title %>
    </div>
    <div class ="field">
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    </div>
    <div class ="action">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
   <tbody>
    <% @users.each do|b| %>
      <tr>
        <!--<td><a href="/users/<>-->
          <!--<img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg">-->
            <td><%= link_to user_path(b.id) do %>
            <%= attachment_image_tag b, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
            <% end %>
            </td>
            <!--</a></td>-->
        <td><%= b.name %></td>
        <td><%= link_to "Show", user_path(b.id) %></td>
      </tr>
    <% end %>
  </tbody>
  <!--<tbody>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>吉田拓未</td>-->
  <!--      <td><a class="user_36384" href="/users/36384">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><
  
  
  ="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>apple</td>-->
  <!--      <td><a class="user_36385" href="/users/36385">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>abcd</td>-->
  <!--      <td><a class="user_36386" href="/users/36386">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>ggg</td>-->
  <!--      <td><a class="user_36387" href="/users/36387">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>西口綾香</td>-->
  <!--      <td><a class="user_36388" href="/users/36388">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>Olivia</td>-->
  <!--      <td><a class="user_36371" href="/users/36371">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>James</td>-->
  <!--      <td><a class="user_36372" href="/users/36372">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>Lucas</td>-->
  <!--      <td><a class="user_36373" href="/users/36373">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>rk</td>-->
  <!--      <td><a class="user_36374" href="/users/36374">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>chikara</td>-->
  <!--      <td><a class="user_36376" href="/users/36376">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>luka</td>-->
  <!--      <td><a class="user_36377" href="/users/36377">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>aaa</td>-->
  <!--      <td><a class="user_36378" href="/users/36378">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>lllllll</td>-->
  <!--      <td><a class="user_36379" href="/users/36379">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>awawa</td>-->
  <!--      <td><a class="user_36380" href="/users/36380">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>笹平颯太</td>-->
  <!--      <td><a class="user_36381" href="/users/36381">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>qaz</td>-->
  <!--      <td><a class="user_36375" href="/users/36375">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>mochita</td>-->
  <!--      <td><a class="user_36382" href="/users/36382">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>kawaura</td>-->
  <!--      <td><a class="user_36389" href="/users/36389">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>jjj</td>-->
  <!--      <td><a class="user_36390" href="/users/36390">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>Yukihiro</td>-->
  <!--      <td><a class="user_36391" href="/users/36391">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>lll</td>-->
  <!--      <td><a class="user_36383" href="/users/36383">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>you</td>-->
  <!--      <td><a class="user_36392" href="/users/36392">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>aaaaaaaa</td>-->
  <!--      <td><a class="user_36393" href="/users/36393">Show</a></td>-->
  <!--    </tr>-->
  <!--    <tr>-->
  <!--      <td><img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"></td>-->
  <!--      <td>wasabi </td>-->
  <!--      <td><a class="user_36394" href="/users/36394">Show</a></td>-->
  <!--    </tr>-->
  <!--</tbody>-->
</table>
  </div>
  </div>
</div>
      </main>